name: Build with tests
run-name: Build with tests build by ${{ github.actor }} 🚀
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  DISPLAY: ":99"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"
  OPENJFX_VERSION: "21"

jobs:
  Build:
    runs-on: ${{ inputs.os }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          java-package: 'jdk+fx'
          distribution: 'zulu'

      - name: Cache Gradle Resources
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux'
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Add code coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        if: github.event_name == 'pull_request'
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
            token: ${{ secrets.GITHUB_TOKEN }}
            min-coverage-overall: 50
            min-coverage-changed-files: 50