name: CI TestFX Build
run-name: CI TestFX build by ${{ github.actor }} 🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-With-Tests-Windows:
    uses: ./github/workflows/build-with-tests.yml
    with:
      os: windows-latest

  Build-With-Tests-Linux:
    uses: ./github/workflows/build-with-tests.yml
    with:
      os: ubuntu-latest

  Build-With-Tests-Mac:
    uses: ./github/workflows/build-with-tests.yml
    with:
      os: macos-latest

  Dependency-Submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2